import './global.css';

import { Open_Sans } from '@next/font/google';

const openSans = Open_Sans({
  subsets: ['latin', 'cyrillic-ext'],
  weight: ['400', '500', '600', '700'], // Adjust weights as needed
});

export const metadata = {
  title: 'Welcome to ger-gurus',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
