name: Example-project Deployment
run-name: Example-project is being deployed
env:
  VERCEL_ORG_ID: ${{ secrets.EXAMPLE_PROJECT_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.EXAMPLE_PROJECT_VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 97-example-project-deployment
jobs:
  DeployApp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - name: 'Install Vercel CLI'
        run: npm i -g vercel@latest

      - name: 'Copy env variables'
        run: |
          mkdir .vercel
          cp -r ./apps/example-project/vercel.json .vercel/project.json

      - name: 'Build the app'
        run: vercel build --prod

      - name: 'Deploy to Vercel'
        run: vercel --prebuilt --prod --token=${{ secrets.EXAMPLE_PROJECT_VERCEL_TOKEN }}
